name: learninglens_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  editable: ^2.0.0  
  flutter_dotenv: ^5.1.0
  xml: ^6.2.2
  http: ^1.2.1
  flutter_quill: ^10.8.0
  english_words: ^4.0.0
  provider: ^6.0.0
  cached_network_image: ^3.4.1
  image_network: ^2.5.6
  path: ^1.8.0
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.0.8
  logger: ^1.4.0
  google_sign_in: ^6.2.2
  flutter_secure_storage: ^9.2.4
  file_picker: ^9.0.2
  pdf: ^3.10.1
  excel: ^2.0.0
  printing: ^5.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.2    
  build_runner: ^2.4.7 


flutter:
  assets:
    - assets/login_image.png
    - .env

  uses-material-design: true

