// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS7G9Lre-9lTSeCghAFFPm9enEp1FDH24',
    appId: '1:944422012610:web:501753444f6ae7875b5d5b',
    messagingSenderId: '944422012610',
    projectId: 'spring2025-81f5b',
    authDomain: 'spring2025-81f5b.firebaseapp.com',
    storageBucket: 'spring2025-81f5b.firebasestorage.app',
    measurementId: 'G-KBCTH5BD5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt3q9f16WvUspQWQ_xhqAvE9mvNH70SGg',
    appId: '1:944422012610:android:a205c56c9180152b5b5d5b',
    messagingSenderId: '944422012610',
    projectId: 'spring2025-81f5b',
    storageBucket: 'spring2025-81f5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgZeA-pUaDnsalTM40eWrTtWDBXKLacVE',
    appId: '1:944422012610:ios:c68887c565b144685b5d5b',
    messagingSenderId: '944422012610',
    projectId: 'spring2025-81f5b',
    storageBucket: 'spring2025-81f5b.firebasestorage.app',
    iosBundleId: 'com.umgc.memoryminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgZeA-pUaDnsalTM40eWrTtWDBXKLacVE',
    appId: '1:944422012610:ios:1c73d37a831e3c015b5d5b',
    messagingSenderId: '944422012610',
    projectId: 'spring2025-81f5b',
    storageBucket: 'spring2025-81f5b.firebasestorage.app',
    iosBundleId: 'com.example.stmlApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS7G9Lre-9lTSeCghAFFPm9enEp1FDH24',
    appId: '1:944422012610:web:ef76cd8cab15eaf35b5d5b',
    messagingSenderId: '944422012610',
    projectId: 'spring2025-81f5b',
    authDomain: 'spring2025-81f5b.firebaseapp.com',
    storageBucket: 'spring2025-81f5b.firebasestorage.app',
    measurementId: 'G-64MQC19KTL',
  );
}
