// Mocks generated by Mockito 5.4.5 from annotations
// in yappy/test/database_helper.mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;
import 'package:yappy/services/database_helper.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i3.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> insertUser(Map<String, dynamic>? user) =>
      (super.noSuchMethod(
            Invocation.method(#insertUser, [user]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateUser(Map<String, dynamic>? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteUser(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> insertVehicle(Map<String, dynamic>? vehicle) =>
      (super.noSuchMethod(
            Invocation.method(#insertVehicle, [vehicle]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateVehicle(Map<String, dynamic>? vehicle) =>
      (super.noSuchMethod(
            Invocation.method(#updateVehicle, [vehicle]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteVehicle(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVehicle, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> insertVehicleMaintenance(Map<String, dynamic>? maintenance) =>
      (super.noSuchMethod(
            Invocation.method(#insertVehicleMaintenance, [maintenance]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateVehicleMaintenance(Map<String, dynamic>? maintenance) =>
      (super.noSuchMethod(
            Invocation.method(#updateVehicleMaintenance, [maintenance]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteVehicleMaintenance(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVehicleMaintenance, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> insertTranscript(Map<String, dynamic>? transcript) =>
      (super.noSuchMethod(
            Invocation.method(#insertTranscript, [transcript]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateTranscript(Map<String, dynamic>? transcript) =>
      (super.noSuchMethod(
            Invocation.method(#updateTranscript, [transcript]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteTranscript(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTranscript, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllTranscripts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTranscripts, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getTranscriptById(int? transcriptId) =>
      (super.noSuchMethod(
            Invocation.method(#getTranscriptById, [transcriptId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<int> insertOrder(Map<String, dynamic>? order) =>
      (super.noSuchMethod(
            Invocation.method(#insertOrder, [order]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateOrder(Map<String, dynamic>? order) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrder, [order]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrder, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> insertOrderItem(Map<String, dynamic>? orderItem) =>
      (super.noSuchMethod(
            Invocation.method(#insertOrderItem, [orderItem]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateOrderItem(Map<String, dynamic>? orderItem) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderItem, [orderItem]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteOrderItem(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrderItem, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getMenuItems() =>
      (super.noSuchMethod(
            Invocation.method(#getMenuItems, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> insertMenuItem(Map<String, dynamic>? menuItem) =>
      (super.noSuchMethod(
            Invocation.method(#insertMenuItem, [menuItem]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateMenuItem(Map<String, dynamic>? menuItem) =>
      (super.noSuchMethod(
            Invocation.method(#updateMenuItem, [menuItem]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteMenuItem(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMenuItem, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> insertSpecialRequest(Map<String, dynamic>? specialRequest) =>
      (super.noSuchMethod(
            Invocation.method(#insertSpecialRequest, [specialRequest]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateSpecialRequest(Map<String, dynamic>? specialRequest) =>
      (super.noSuchMethod(
            Invocation.method(#updateSpecialRequest, [specialRequest]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteSpecialRequest(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSpecialRequest, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getDoctorVisits() =>
      (super.noSuchMethod(
            Invocation.method(#getDoctorVisits, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> insertDoctorVisit(Map<String, dynamic>? doctorVisit) =>
      (super.noSuchMethod(
            Invocation.method(#insertDoctorVisit, [doctorVisit]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateDoctorVisit(Map<String, dynamic>? doctorVisit) =>
      (super.noSuchMethod(
            Invocation.method(#updateDoctorVisit, [doctorVisit]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteDoctorVisit(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDoctorVisit, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> insertPatient(Map<String, dynamic>? patient) =>
      (super.noSuchMethod(
            Invocation.method(#insertPatient, [patient]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updatePatient(Map<String, dynamic>? patient) =>
      (super.noSuchMethod(
            Invocation.method(#updatePatient, [patient]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deletePatient(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePatient, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<Map<String, dynamic>?> getDoctorVisitById(int? visitId) =>
      (super.noSuchMethod(
            Invocation.method(#getDoctorVisitById, [visitId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getDoctorVisitsByPatientId(
    int? patientId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDoctorVisitsByPatientId, [patientId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getVehicleMaintenanceById(
    int? maintenanceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleMaintenanceById, [maintenanceId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<Map<String, dynamic>?> getVehicleById(int? vehicleId) =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleById, [vehicleId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<int>> getVehicleIdsByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleIdsByUserId, [userId]),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);

  @override
  _i4.Future<List<int>> getTranscriptIdsByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTranscriptIdsByUserId, [userId]),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);

  @override
  _i4.Future<List<int>> getMaintenanceIdsByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMaintenanceIdsByUserId, [userId]),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);

  @override
  _i4.Future<List<int>> getItemIdsByOrderId(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getItemIdsByOrderId, [orderId]),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);

  @override
  dynamic saveTranscript({
    required int? userId,
    required int? transcriptId,
    required String? text,
    required String? industry,
  }) => super.noSuchMethod(
    Invocation.method(#saveTranscript, [], {
      #userId: userId,
      #transcriptId: transcriptId,
      #text: text,
      #industry: industry,
    }),
  );

  @override
  dynamic saveTranscriptAiResponse({
    required int? userId,
    required int? transcriptId,
    required String? text,
    required String? aiResponse,
    required String? industry,
  }) => super.noSuchMethod(
    Invocation.method(#saveTranscriptAiResponse, [], {
      #userId: userId,
      #transcriptId: transcriptId,
      #text: text,
      #aiResponse: aiResponse,
      #industry: industry,
    }),
  );

  @override
  _i4.Future<List<String>> searchTranscripts(String? query, String? industry) =>
      (super.noSuchMethod(
            Invocation.method(#searchTranscripts, [query, industry]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<Map<String, String>?> getTranscriptDetails(String? entry) =>
      (super.noSuchMethod(
            Invocation.method(#getTranscriptDetails, [entry]),
            returnValue: _i4.Future<Map<String, String>?>.value(),
          )
          as _i4.Future<Map<String, String>?>);

  @override
  _i4.Future<int> insertDocument(
    int? transcriptId,
    String? fileName,
    List<int>? fileBytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertDocument, [
              transcriptId,
              fileName,
              fileBytes,
            ]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<Map<String, String>?> getTranscriptTextDataAndIndustryById(
    int? transcriptId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTranscriptTextDataAndIndustryById, [
              transcriptId,
            ]),
            returnValue: _i4.Future<Map<String, String>?>.value(),
          )
          as _i4.Future<Map<String, String>?>);

  @override
  _i4.Future<Map<String, dynamic>?> getDocumentAndIndustryById(
    int? transcriptId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDocumentAndIndustryById, [transcriptId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<int> insertAiResponse(int? transcriptId, String? aiResponse) =>
      (super.noSuchMethod(
            Invocation.method(#insertAiResponse, [transcriptId, aiResponse]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<bool> updateTranscriptDocument(
    int? transcriptId,
    List<int>? documentBytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTranscriptDocument, [
              transcriptId,
              documentBytes,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
