name: memoryminder
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  logging: ^1.2.0
  path_provider: ^2.1.2
  permission_handler: ^11.2.1
  url_launcher: ^6.2.4

  # Firebase packages
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.10
  firebase_crashlytics: ^3.4.14
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.5.0  # Added Firebase Storage

  # Authentication & Security
  local_auth: ^2.1.8

  # Location Services
  geolocator: ^10.1.0
  geocoding: ^3.0.0

  # Database
  sqflite: ^2.3.2

  # Date & Time
  moment_dart: ^4.0.1
  timeago: ^3.6.1

  # Media handling
  video_thumbnail: ^0.5.3
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  flutter_sound: ^9.2.13
  chewie: ^1.7.4
  video_player: ^2.8.2
  image_gallery_saver: ^2.0.3
  external_path: ^2.0.1

  # AWS Services
  aws_rekognition_api: ^2.0.0
  aws_s3_api: ^2.0.0
  aws_transcribe_api: ^2.0.0

  # AI & Speech
  speech_to_text: ^6.6.0
  dart_openai: ^5.0.0
  flutter_tts: ^4.0.1

  # UI Components
  avatar_glow: ^3.0.1
  flutter_local_notifications: ^16.3.2
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/welcome_image.png
    - assets/images/
    - assets/icons/
    - assets/icons/app_icon.png
    - assets/seed_data_files/